### ISSUE TITLE
Error running `civicrm-docker-install`

### ISSUE THREAD

**Issue by tgranqvist** [civicrm/civicrm-docker#34]
I'm following the guide in this repo to run CiviCRM via Docker. As I run this

I run into the following issue when executing the `civicrm-docker-install` script.

> In CmsBootstrap.php line 67:
> 
>   Failed to parse or find a CMS null

I tweaked the compose file a bit, it looks like this.

```
services:
  app:
    image: civicrm/civicrm:6.2.0-php8.2
    ports:
      - 8760:80 # CiviCRM will be available on port 8760.
    restart: unless-stopped
    volumes:
      - private:/var/www/html/private
      - public:/var/www/html/public
      - ext:/var/www/html/ext
    env_file:
        - crm.env
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    env_file:
        - db.env

volumes:
  private:
  public:
  ext:
  db:
```

The environment files look as follows:

crm.env
```
CIVICRM_ADMIN_USER=abcd
CIVICRM_ADMIN_PASS=...
CIVICRM_DB_HOST=db
CIVICRM_DB_PORT=3306
CIVICRM_DB_NAME=civicrm
CIVICRM_DB_USER=civicrm
CIVICRM_DB_PASSWORD=abc123
CIVICRM_UF_BASEURL=http://192.168.10.10:8760
```

db.env
```
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=civicrm
MYSQL_USER=civicrm
MYSQL_PASSWORD=abc123
```
